### ISSUE TITLE
TypeError: Object .. has no method 'split'

### ISSUE THREAD

**Issue by dotherightthing** [kevinlacotaco/grunt-todos#7]
Hi,

I'm using this plugin for the first time, and am getting this error:

```
TypeError: Object 
[insert contents of a JS file here]
 has no method 'split'
    at fileReader (/Users/Dan/Websites/project_name/_svn/htdocs/node_modules/grunt-todos/lib/grep.js:10:26)
    at fs.readFile (fs.js:176:14)
    at fs.close (/Users/Dan/Websites/project_name/_svn/htdocs/node_modules/grunt/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:90:5)
    at Object.oncomplete (fs.js:297:15)
```

Gruntfile.js config:

```
paths: {
  resources:        'resources',
  scripts:          '<%= paths.resources %>/scripts',
},

// TODOS
todos: {
  options: {
    priorities: {
      low : /TODO/, // default
      med : /FIXME/, // default
      high : null // default
    },
    verbose: false //  only files with todos will be mentioned.
    // Task-specific options go here.
  },
  src : [
    '<%= paths.scripts %>/*.js' // target all .js files
  ]
},
```

I get the same error when running the plugin over CSS files.

```
"devDependencies": {
    "grunt": "~0.4.1",
    "grunt-todos": "~0.2.0"
}
```

Thanks,
Dan

**Comment by ryan-roemer** [comment]
I hit the same thing too. It looks like it's the `grep.js` file, and specifically that the file reader can't handle directories. I had Requirejs source, which has directories with `*.js` extensions, and that was the root cause for me.

Should ideally gracefully handle this.

**Comment by IbeVanmeenen** [comment]
Same problem here... Get the same error with this setup (underscore):

```
todos: {
    options: {
        verbose: false
    },
    src : _.union(KunstmaanWebsiteBundle.js, KunstmaanWebsiteBundle.scss, KunstmaanWebsiteBundle.twig)
}
```

Any idea how to fix this?

**Comment by Bartvds** [comment]
It may be a little late news but I adopted this project and this should work now. 

The filereader does a `stat.isFile()` and supports utf8.

See #10 for more info.
